### PR TITLE
Add "typescript-support" as a .ts/x handler

### PR DESCRIPTION
**Pull request by AviVahl**
Maintained, supports latest TypeScript 3, and handles multiple/no tsconfigs properly.

https://github.com/AviVahl/typescript-tools/tree/master/packages/typescript-support

### CODE REVIEW

**Comment by phated** [comment]
@AviVahl we're not really looking to incorporate another typescript compiler.  If you are using with gulp, you can always just require it with the `--require` flag.

**Comment by phated** [comment]
@tkellen every library we add here adds maintenance over on the gulp repo because people open issues for the "failed to load ..." messages constantly.  The library submitted is @AviVahl's personal project that seems to be very new and quite unused.  The gulp stance has generally been to avoid splitting communities and ts-node has 867,920 weekly downloads compared to 500.

**Comment by tkellen** [comment]
@phated Thanks for the additional context. Is there some level of activity that would signal for you something is popular enough for inclusion?

@AviVahl Have you tried to get the behavior you're seeking into `ts-node` proper? I know @blakeembrey is pretty great about hearing feedback!

**Comment by blakeembrey** [comment]
@AviVahl If you'd like to get support for your customizations into `ts-node`, I'd love to work with you to make it happen. It'd be useful to reduce the number of variations of packages to just one, as you have shown above. From your package, it looks like the primary difference is just loaded different `tsconfig.json` files. A similar feature is actually being looked at added to `ts-node` today, only declarative in config since most people have not needed the automatic behavior of looking configuration up - when you add `extends` and other TypeScript features into the mix.

**Comment by AviVahl** [comment]
Hi @blakeembrey my use case has actually included usage of "extends"... I just had more `tsconfig.json` files scattered around my repo, at points where I wanted to isolate folders to differents "lib"s or "types" (usually packages). Would be great if `ts-node` supported [such scenario](https://github.com/wixplosives/sample-monorepo) as well, but I do understand this might not be the common typescript use-case... 

While I see the obvious benefit in having a single integration package used by everyone (_one ring to rule them all_), I also appreciate the upsides of having multiple open source projects tackling the same issue, each with their own approach and set of constrictions/choices/tradeoffs. Users get more choices, and projects push each other to improve.

I also built my integration in a way that I can reuse parts for another open source tooling project I'm working on atm, so there's that need as well.

With the above being said, I'd be happy to collaborate with you (@blakeembrey), even if it's just to pick your brain about various TypeScript-related stuff :) Are you online in any public gitter/slack?

Apologies for taking this PR bit off-topic.

**Comment by contra** [comment]
I would say as a general rule 1 person = ~100 downloads/mo (at least on my projects, where I know I'm the only user), so 5000 downloads/mo (50 people) seems reasonable to be added.

@phated thoughts?

**Comment by tkellen** [comment]
That works for me. Assuming @phated agrees, I think a note in the README or the addition of a CONTRIBUTING file with this outlined is warranted. I'd like to give potential contributors a clear path to success.

**Pull request closed without merging**
