### PR TITLE
Fixes #39

### LINKED ISSUE #39: babel-register compiles .js files; should only handle .babel.js
Babel frequently has bugs (at least, I've hit many) so there's no reason to have babel compiling `.js` files when it's not necessary.

You can use babel-register's `only` option to avoid transpiling files unless they actually end in `.babel.js`
https://github.com/js-cli/js-interpret/blob/master/index.js#L2-L12

```
'.babel.js': [
    {
      module: 'babel-register',
      register: function (module) {
        module({
          // register on .js extension due to https://github.com/joyent/node/blob/v0.12.0/lib/module.js#L353
          // which only captures the final extension (.babel.js -> .js)
          extensions: '.js',
          only: /\.babel\.js$/
        });
      }
    },
    // ... do the same for other entries in this array
```

### PR DESCRIPTION
**Pull request by cspotcode**

### CODE REVIEW

**Comment by phated** [comment]
This option seems to date pretty far back (I'm seeing it referenced in 6to5 source).  I think that it wasn't documented when we implemented this and I didn't dig into the source.  If we bring this in, I think it needs to be marked as a breaking change since people are probably relying on the current behavior.  I think this will add a ton of overhead to people that are transpiling every file since it has to execute a regexp against each part of the path (according to some changelog messages I read).  @tkellen thoughts?

**Comment by phated** [comment]
Side note: this can be adjusted within the .babelrc file I believe (again, going by commit/changelog messages).

**Comment by cspotcode** [comment]
Here's where it's implemented in the current babel:
https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L87-L93
https://github.com/babel/babel/blob/master/packages/babel-core/src/util.js#L114-L133
https://github.com/babel/babel/blob/master/packages/babel-core/src/util.js#L140-L146

According to that code, it doesn't execute a regexp against each part of the path; it executes once against the full path.

**Comment by phated** [comment]
@cspotcode it seems that the "check against each part of the path" is for the `node_modules` folder when neither `only` nor `ignore` is specified.  By turning this option on, you are making babel traverse the `node_modules` tree again. I believe the way this should be handled is in your own `.babelrc` file.

**Comment by tkellen** [comment]
I think @phated is likely correct that people are relying on the side effects of our current configuration. 

I am cautiously in favor of this change if we can provide guidance for those upstream (e.g. gulp, webpack, etc) on how warn around this.

**Comment by phated** [comment]
@tkellen I still don't think this is a good solution.  For people that need to be really strict on transpiled files, they can use the .babelrc as an override.

**Comment by tkellen** [comment]
I think our current functionality is an overreach but I'm willing to leave it as is if you feel super strongly there is no way we can "fix" this without causing harm to the ecosystem around this module. I would love it if we could brainstorm a bit about what that fix might look like before we dismiss this.

**Comment by cspotcode** [comment]
I poked around with babel and updated the PR based on my findings.  The PR now ignores `node_modules` like Babel.  If an end-user wants to transpile all .js files, they can add this to their `hackerfile.babel.js`:

```js
// hackerfile.babel.js
require('babel-register')({ignore: `${__dirname}/node_modules/`, extensions: ['.js', '.es', '.es6', '.jsx']});
```
Here's the same thing, but with more comments and clarification:
```js
// hackerfile.babel.js
import * as path from 'path';
require('babel-register')({
  // Good enough
  ignore: `${__dirname}/node_modules/`
  // Technically more correct than the above
  ignore: (f) => path.normalize(f).indexOf(path.join(__dirname, 'node_modules/')) === 0,
  // If you want extensions other than .js
  extensions: ['.es', '.jsx']
});

require('lodash'); // will not be transpiled because it's in node_modules
module.exports = require('./other-es6-code'); // will be transpiled
```
Turns out babel-register keeps the `ignore` and `only` options passed programmatically separate from the options it gets from a .babelrc file.  (one source does not override the other; they both take effect)

Anyway, I don't have a strong opinion for or against merging this PR.  But I did the research anyway, so I'm sharing with you.

**Comment by phated** [comment]
Now that I've released v1.2 with babel7 and esm support, I'd like to revisit this and get it shipped in a 2.0 (along with the solution to #54).  I'm definitely considering this breaking but I'm fine bumping to 2.0

**Comment by NitroBAY** [comment]
Okay so @phated if you're fine with it I may create a PR based on current master branch and reimplement the idea of this PR and implement #54 in this new PR so we may have a interpret 2.0 that works correctly with monorepo (actually I need interpret 2.0 because my /client require a file in its webpack.config.babel.js that is in its parent folder (the application that has the client and the server and some stuff required by both the server and the client))

**Comment by NitroBAY** [comment]
> Now that I've released v1.2 with babel7 and esm support, I'd like to revisit this and get it shipped in a 2.0 (along with the solution to #54). I'm definitely considering this breaking but I'm fine bumping to 2.0



> Okay so @phated if you're fine with it I may create a PR based on current master branch and reimplement the idea of this PR and implement #54 in this new PR so we may have a interpret 2.0 that works correctly with monorepo (actually I need interpret 2.0 because my /client require a file in its webpack.config.babel.js that is in its parent folder (the application that has the client and the server and some stuff required by both the server and the client))

@phated see #58

**Comment by phated** [comment]
Completed by #58

**Pull request closed without merging**
